## default connection pool
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5


logging.pattern.console=%-5level %logger{36} - %msg%n

## PostgerSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/projeto_vendas_online
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

#drop and create table again, good for testing, comment this in production
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=*

