server.port=8888
spring.application.name=config-server
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config
spring.security.user.name=root
spring.security.user.password=root
#spring.application.name=cliente-service
#spring.cloud.config.uri=http://localhost:8888
#spring.config.import=configserver:
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
